# Site settings
title: Notes about software development
email: mtmk@suzen.net
description: > # this means to ignore newlines until "baseurl:"
  Ziya Suzen (Maxwell Troy)'s personal notes on software development
  and related technical subjects.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ziya.suzen.net" # the base hostname & protocol for your site
twitter_username: maxwelltroymk
github_username:  mtmk

# Build settings
markdown: kramdown

disqusid: "notesaboutsoftwaredevelopment"
